version: '2'
services:
  vuedemosearch:
    container_name: vue-demo-search
    hostname: vue-demo-search
    image: vue-demo-search
    build: ..
    ports:
        - "20491:8080"
    volumes:
        - ../build/:/usr/src/app/build
        - ../config/:/usr/src/app/config
        - ../src/:/usr/src/app/src
        - ../static/:/usr/src/app/static
        - ../test/:/usr/src/app/test
        - ../dist/:/usr/src/app/dist
    command: ["npm", "run", "dev"]
